name: syn_cli
version: 1.8.2
homepage: https://github.com/jonataslaw/syn_cli
description: Official CLI for GetX™ framework to build Flutter and Server
  Applications easily
environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  ansicolor: ^2.0.1
  collection: ^1.15.0
  dart_style: ^2.0.1
  dcli: 3.4.0
  http: ^0.13.4
  intl: 0.18.0
  meta: 1.11.0
  path: ^1.8.0
  process_run: ^0.12.2
  pubspec: ^2.0.1
  recase: ^4.0.0
  version: ^2.0.0
  yaml: ^3.1.0

dev_dependencies:
  lints: ^4.0.0

executables:
  get: syn
  getx: syn
